import type { LucideIcon } from "lucide-react";

import {
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Book,
  Bookmark,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  Clock,
  Code2,
  Compass,
  Container,
  Copy,
  CornerDownLeft,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Grid2x2,
  Grid3x3,
  Heart,
  HeartPulse,
  Home,
  Layers,
  LayoutGrid,
  Link2,
  ListChecks,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Package,
  Plus,
  Quote,
  Rocket,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  TrendingUp,
  Trophy,
  Truck,
  User,
  UserPlus,
  Watch,
  X,
} from "lucide-react";

export const lucideIcons = {
  home: Home,
  bookmark: Bookmark,
  code: Code2,
  flame: Flame,
  "list-checks": ListChecks,
  lock: Lock,
  plus: Plus,
  quote: Quote,
  shuffle: Shuffle,
  star: Star,
  "file-text": FileText,
  compass: Compass,
  "trending-up": TrendingUp,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  check: Check,
  copy: Copy,
  link: Link2,

  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  shirt: Shirt,
  watch: Watch,
  "credit-card": CreditCard,
  truck: Truck,
  folder: Folder,

  user: User,
  "user-plus": UserPlus,
  "log-in": LogIn,

  book: Book,
  "book-open": BookOpen,
  search: Search,
  heart: Heart,
  "heart-pulse": HeartPulse,
  sparkles: Sparkles,

  cpu: Cpu,
  database: Database,
  server: Server,
  terminal: Terminal,
  monitor: Monitor,
  rocket: Rocket,
  container: Container,
  box: Box,
  boxes: Boxes,
  layers: Layers,
  moon: Moon,
  sun: Sun,

  menu: Menu,
  close: X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  settings: Settings,

  "grid-2x2": Grid2x2,
  "grid-3x3": Grid3x3,
  "layout-grid": LayoutGrid,

  "at-sign": AtSign,
  mail: Mail,
  "share-2": Share2,
  outline: AlignLeft,
  FileText: FileText,
  CornerDownLeft: CornerDownLeft,

  "map-pin": MapPin,

  "circle-check": CircleCheck,
  "check-circle-2": CheckCircle2,
  shield: Shield,

  calendar: Calendar,
  diamond: Diamond,
  flag: Flag,

  "flask-conical": FlaskConical,
  target: Target,
  trophy: Trophy,
} satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof lucideIcons;
